name: clinical_data_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.3
  - numpy=1.24.3
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - jupyter=1.0.0
  - ipykernel=6.27.1
  - pip
  - pip:
    - statsmodels==0.14.0
    - plotly==5.18.0
    - xgboost==2.0.3
    - missingno==0.5.2
    - python-dateutil==2.8.2


